on:
  issue_comment:
    types: [created]
    
name: Deploy POI to Production

jobs:
  react-on-issue-comment-not-approved:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Approve POI Deploy to Production') && startsWith(github.event.comment.body, '/approve')
    steps:
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Swap the slot
      run: az webapp deployment slot swap  -g openhackggp0ljh0rg -n openhackggp0ljh0poi --slot staging --target-slot production

    - name: Azure Logout
      run: az logout
