name: POI CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'apis/poi/**'
  
  push:
    branches: [ master ]
    paths:
      - 'apis/poi/**'
      - '.github/workflows/poi-ci.yml'
          

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore apis/poi/poi.sln
    - name: Build
      run: dotnet build apis/poi/poi.sln --no-restore
    - name: Test
      run: dotnet test apis/poi/tests/UnitTests/UnitTests.csproj --no-restore 
    
##### the following creates an issue if the POI build fails #####
    - name: File an issue if the build fails
      if: failure()
      uses: actions/github-script@0.9.0
      with:
        script: |
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'POI Build Failed',
            assignees: [ '${{ github.actor }}' ],
            body: 'POI Build Failed, Pls fix the code'
            })  
 
