# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  paths:
    include:
    - apis/userprofile

pr:
  branches:
    include:
      - master
  paths:
    include:
    - apis/userprofile

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'apis/userprofile'
    verbose: true
  displayName: 'Install Dependencies'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npm run test'
    workingDirectory: 'apis/userprofile'
    failOnStderr: true
  displayName: 'Run Tests'
Build and deploy JavaScript and Node.js apps - Azure Pipelines
Build and test JavaScript and Node.js apps with Azure Pipelines

